### ISSUE TITLE
(Question) Android iOS interop?

### ISSUE THREAD

**Issue by MG-LSJ** [ksenia312/nearby_service#1]
Not an issue but a question

Does this support connections between iOS and Android devices?

**Comment by ksenia312** [comment]
Hello, unfortunately no
This is a limitation of Multipeer Connectivity on iOS, we cannot get the device address on the network. So we cannot create a custom socket for communication without device addresses

**Comment by MG-LSJ** [comment]
> Hello, unfortunately no This is a limitation of Multipeer Connectivity on iOS, we cannot get the device address on the network. So we cannot create a custom socket for communication without device addresses

Hi, I think it could be possible with Google's nearby connections on iOS. https://developers.google.com/nearby/connections/overview. (I don't have enough knowledge of Flutter otherwise would have made a PR)

**Comment by Princewil** [comment]
> Not an issue but a question
> 
> Does this support connections between iOS and Android devices?

Was about to ask this same question. Thanks for bring it up
